In [1]:
import numpy as np

1. Создать вектор (одномерный массив) размера 10, заполненый нулями

In [2]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Создать вектор (одномерный массив) размера 10, заполненый нулями

In [3]:
vector = np.ones(10)
vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. Создать вектор размера 10, заполненный числом 2.5

In [4]:
vector = np.full(10, 2.5)
vector

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

4. Создать вектор заполненный нулями, но пятый элемент равен 1

In [5]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

5. Создать вектор со значениями от 10 до 49

In [6]:
vector = np.arange(10, 50)
vector


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

6. Развернуть вектор (первый становится последним)

In [7]:
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
reversed_vector = np.flip(vector)
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

7. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
arr = np.arange(9)

matrix = arr.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [10]:
arr = np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4]),)

9. Создать массив 3x3x3 со случайными значениями

In [11]:
arr = np.random.rand(3, 3, 3)

print(arr)


[[[0.63593057 0.45330099 0.29157963]
  [0.11797613 0.28881469 0.30147964]
  [0.27156686 0.93237693 0.80343793]]

 [[0.65672055 0.41928472 0.54509814]
  [0.59072575 0.52830497 0.94477759]
  [0.82140434 0.50117371 0.91988468]]

 [[0.61627887 0.10233718 0.13240972]
  [0.74226684 0.08372502 0.19345914]
  [0.26149398 0.43399486 0.5575358 ]]]


10. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [12]:
arr = np.random.randint(1, 10, 10)
print(arr)
print(arr.min())
print(arr.max())

[3 9 3 6 7 4 6 3 7 4]
3
9


11. Создать матрицу с 0 внутри и 1 на границах

In [13]:
matrix = np.ones((3, 3))
np.fill_diagonal(matrix, 0)
matrix

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

12. Создать матрицу 8x8 и заполнить ее в шахматном порядке

In [14]:
chessboard = (np.indices((8, 8)).sum(axis=0) % 2)
chessboard


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

13. Перемножить матрицы 5x3 и 3x2

In [15]:
A = np.random.rand(5, 3)  # 5x3
B = np.random.rand(3, 2)  # 3x2

C = A @ B

print("Матрица A (5x3):\n", A)
print("\nМатрица B (3x2):\n", B)
print("\nРезультат C = A*B (5x2):\n", C)


Матрица A (5x3):
 [[0.3340113  0.09814066 0.38817554]
 [0.92325568 0.63322297 0.66489122]
 [0.08437717 0.33346924 0.94915815]
 [0.50740977 0.14392065 0.43153224]
 [0.45392818 0.43003565 0.09463587]]

Матрица B (3x2):
 [[0.59014973 0.77269752]
 [0.72949655 0.14545829]
 [0.41753541 0.55076074]]

Результат C = A*B (5x2):
 [[0.43078698 0.48615692]
 [1.28440869 1.17170088]
 [0.68936696 0.63646294]
 [0.58461735 0.65067974]
 [0.62110894 0.46542315]]


14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

In [16]:
matrix = np.random.randint(1, 101, (5, 7))

print("Исходная матрица:\n", matrix)

matrix_new = np.delete(matrix, [3, 5], axis=1)

print("\nМатрица после удаления колонок 3 и 5:\n", matrix_new)


Исходная матрица:
 [[60 35 97 35 98 99 87]
 [14 59 86 12 88 97 14]
 [54 39  1 64 91 48 84]
 [61 55 60 47 94  3 18]
 [68  2 48 56 39 36 18]]

Матрица после удаления колонок 3 и 5:
 [[60 35 97 98 87]
 [14 59 86 88 14]
 [54 39  1 91 84]
 [61 55 60 94 18]
 [68  2 48 39 18]]


15. Есть генератор, сделать с его помощью массив

In [17]:
def generate():
    for x in range(10):
        yield x
gen = generate()
array = np.array(list(gen))

array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np

list_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array = np.array(list_2d, dtype=np.int32)

array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [19]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))


True
False


In [20]:
import numpy as np
arr = np.array([1, 2, 3])

arr.flags.writeable = False

print(arr)

arr[0] = 1

[1 2 3]


ValueError: assignment destination is read-only